import type { BridgeSelectFormState } from "./bridgeSelectTypes";

export const BRIDGE_SELECT_INSTALLER_DIRECTORY = [
  { name: "David McVernon", id: "S0606150" },
] as const;

export function createDefaultBridgeSelectForm(): BridgeSelectFormState {
  return {
    jobType: "Solar PV + Battery",
    ownerType: "Individual",
    jobCategory: "",

    firstName: "",
    lastName: "",
    customerFullName: "",
    email: "",
    mobile: "",
    phone: "",
    gstRegistered: "No",

    streetAddress: "",
    suburb: "",
    state: "",
    postcode: "",
    addressType: "Physical",
    unitType: "",
    unitNumber: "",
    poBoxNumber: "",
    postalDeliveryType: "PO Box",
    storeyType: "",
    propertyName: "",
    installationUnitType: "",
    installationUnitNumber: "",
    customerLatitude: "",
    customerLongitude: "",
    installationAddress: "",
    installationPostcode: "",
    installationStreetName: "",
    installationSuburb: "",
    installationState: "",
    installationLatitude: "",
    installationLongitude: "",
    sameInstallationAddressAsCustomer: false,
    propertyType: "Residential",
    storyFloorCount: "",

    nmi: "",
    electricityRetailer: "",
    accountHolderName: "",
    billIssueDate: "",
    electricityBill: null,

    solarIncluded: false,
    panelManufacturer: "",
    panelModel: "",
    panelQuantity: "",
    panelSystemSize: "",
    inverterIncluded: false,
    inverterManufacturer: "",
    inverterSeries: "",
    inverterModel: "",
    inverterQuantity: "",

    batteryIncluded: false,
    batteryManufacturer: "",
    batterySeries: "",
    batteryModel: "",
    batteryQuantity: "",
    batteryCapacity: "",

    connectedType: "On-grid",
    installationStyle: "AC coupling",
    batteryInstallationType: "New",
    batteryInstallationLocation: "",
    existingSolarRetained: "No",
    backupProtectionRequired: "No",
    installerPresenceRequired: "No",
    specialSiteNotes: "",
    customerInstructions: "",
    sitePreparationNotes: "",

    installationDate: "",
    preferredInstallDate: "",
    installationEmail: "",
    installationPhone: "",
    installerName: BRIDGE_SELECT_INSTALLER_DIRECTORY[0].name,
    installerId: BRIDGE_SELECT_INSTALLER_DIRECTORY[0].id,
    designerName: "",
    electricianName: "",
    operationsApplicantName: "",
    operationsContact: "",
    operationsEmail: "",

    pickupLocation: "",
    pickupContactPerson: "",
    pickupContactNumber: "",
    pickupHours: "",
    pickupSalesOrderReference: "",
    deliveryWarehouseNotes: "",

    organisationName: "",
    crmId: "",
    poNumber: "",
    orderReference: "",
    proposalNumber: "",
    retailerEntityName: "",
    stcTraderName: "",
    financialPaymentRebateField: "",

    bstcCount: "",
    isBstcJob: "Yes",
    bstcDiscountOutOfPocket: "",
    vppCapable: "No",
    retailerInvolvedInBattery: "No",
    roomBehindBatteryWall: "No",
    addingCapacityExistingBattery: "No",
    existingNominalOutput: "",
    existingUsableOutput: "",

    prcDistributorAreaNetwork: "",
    batteryPhysicalLocation: "Indoor",
    prcBess1Count: "",
    isBess1Job: "Yes",
    prcBess1Discount: "",
    prcBess2Count: "",
    isBess2Job: "No",
    prcBess2Discount: "",
    prcActivityType: "BESS",

    landTitleType: "",
    landZoning: "",
    streetNumberRmb: "",
    lotNumber: "",
    lotDpNumber: "",

    signedProject: null,
    solarProposal: null,
    uploadElectricityBill: null,
    sitePhotos: null,
    supportingDocuments: null,
  };
}
